spring:
  application:
      name: recipes-api
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin

  datasource:
    url: jdbc:postgresql://postgres:5432/abnamro
    username: admin
    password: admin

  flyway:
    enabled: true
    locations: classpath:db/migration
    baselineOnMigrate: true

#logging:
#  level:
#    root: debug
